export const AUTH_USER_EXIST = "AUTH_USER_EXIST";
export const AUTH_STATUS_BLOCKED = "AUTH_STATUS_BLOCKED";
export const AUTH_INVALID_OLD_PASSWORD = "AUTH_INVALID_OLD_PASSWORD";
export const AUTH_INVALID_REQUEST = "AUTH_INVALID_REQUEST";
export const AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED";
